### ISSUE TITLE
CaptureMetrics will crash the entire program if a handler panics

### ISSUE THREAD

**Issue by heyimalex** [felixge/httpsnoop#2]
Foreword: Hey there, I really like this package (and I _really_ like not needing to maintain my own).

Because you're running the http handler in a new goroutine, if the handler panics it will take down the whole program. The standard http server actually recovers from panics in handlers, so crashing completely is pretty bad.

There easiest solution is just to move to locks. Code gets simpler and faster.

Little program to reproduce:

```go
package main

import (
    "log"
    "net/http"
    "net/http/httptest"
    "github.com/felixge/httpsnoop"
)

func main() {
    badHandler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
        panic("oh no!")
    })

    server1 := httptest.NewServer(badHandler)
    defer server1.Close()

    server2 := httptest.NewServer(metricsMiddleware(badHandler))
    defer server2.Close()

    // This should cause the server to print out a panic traceback, but not to actually die.
    http.Get(server1.URL)
    log.Println("Program continued executing!!!")

    http.Get(server2.URL)
    log.Println("Program died so I won't get printed :(")
}

func metricsMiddleware(h http.Handler) http.Handler {
    return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
        metrics := httpsnoop.CaptureMetrics(h, w, r)
        log.Printf("response code was: %d", metrics.Code)
    })
}
```

**Comment by felixge** [comment]
Ouch, I forgot about this edge case. Thanks for bringing it up! I agree that it needs fixing, and I agree that locks might be the way to go. Will try to make a patch later today.

Anyway, please allow me to rant on this subject a bit. I personally find the decision to automatically recover from panics inside of Go handlers to be absolutely insane. Let's say you're using a 3rd party database/sql implementation, and your handler somehow triggers a panic inside of it. Now, instead of safely restarting the process, the Go core will recover the panic, and continue handling requests. However, there is no guarantee that the state of your sql/database driver (e.g. one of the *conn struct its using internally) isn't corrupted now. The func that was panic'ing may have forgotten to release a lock, cleanup some struct field, or similar. And while it's theoretically possible to write libraries in a way that makes them "panic safe" by using `defer` and/or being very careful about not panic'ing to begin with, I don't like the idea of having to audit my entire stack of libraries used from within my handlers to verify this property. So in the worst case, my application might stay up and running, but all http requests fail or block indefinitely due to my database/sql driver state being corrupted until I manually restart the process.

Okay, enough rant. I suppose this isn't a huge problem for most people, due to a few reasons:

* Not all libraries are stateful or expose long-living mutable data structures.
* Go doesn't use the callback pattern much, therefor a panic in my own code is unlikely to corrupt the state of a library I'm using library.
* `defer` helps a lot with consistently cleaning up, even in the presence of panics.
* Go development usually involves less 3rd party libraries than other languages in my experience

Anyway, I still absolutely hate the idea of blindly recovering from handler panics.

I just had to get this out of my system ... :)
