### ISSUE TITLE
runtime.newStack getting called from Wrap?

### ISSUE THREAD

**Issue by ankon** [felixge/httpsnoop#28]
We're looking at CPU profiles of our servers, and noticed that there's a considerable amount of `runtime.newStack` getting attributed to httpsnoop.Wrap:
![Screenshot 2024-02-06 at 13 36 31](https://github.com/felixge/httpsnoop/assets/1210641/4b115700-984e-445e-bf59-8bbcfa18b874)

I cannot find any explicit code doing that though, do you have any pointers here that could help us track this down (and ultimately eliminate)?

**Comment by felixge** [comment]
Sorry for the late reply. What you're seeing is the stack of the goroutine growing from it's initial size (probably 2 KiB) to a bigger size (probably 4 KiB) due to the initially stack having filled up, and more space being required by the current callee (in this case `httpsnooop.Wrap`. The fact that this is happening in httpsnoop is coincidental. If you were to add another middleware, you'd probably see the stack growth happening in those functions. Or if you remove a middleware, you'd see the stack growth in your final handler code.

I'm closing this issue for now because this is more of a general Go performance topic best discussed on either the Go issue tracker (there are already issues for this, please search before opening a new one) or similar forums.
